# Generated by Django 2.2.2 on 2019-06-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podjetje', models.CharField(max_length=20)),
                ('reference', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('datum_ponudbe', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_knj_ponudbe', models.DateTimeField(blank=True, null=True)),
                ('stranka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
